from flask import Flask
from config import DevelopmentConfig
#you

app = Flask(__name__)
app.config.from_object(DevelopmentConfig)
#mysql = MySQL(app)
#app.config['MYSQL_HOST'] = 'localhost'
#app.config['MYSQL_USER'] = 'root'
#app.config['MYSQL_PASSWORD'] = 'summer'


# # This hook ensures that a connection is opened to handle any queries
# # generated by the request.
# @app.before_request
# def _db_connect():
#     database.connect()
# 
# # This hook ensures that the connection is closed when we've finished
# # processing the request.
# @app.teardown_request
# def _db_close(exc):
#     if not database.is_closed():
#         database.close()